#!/usr/bin/env python3
"""Generate a `tools.md` file documenting every MCP tool exposed by the server.

The script imports the live ``FastMCP`` instance from ``mcp_ssh`` and asks it for
the registered tools, so the output always reflects what clients actually see
(name, description and the JSON-schema of each tool's arguments).

Usage:
    python scripts/generate_tools_md.py [-o OUTPUT]
"""
from __future__ import annotations

import argparse
import asyncio
import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List

# Make sure we can import `mcp_ssh` regardless of the current working directory.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from mcp_ssh import mcp  # noqa: E402


def _format_default(value: Any) -> str:
    if value is None:
        return "`null`"
    return f"`{value!r}`"


def _render_parameters(parameters: Dict[str, Any]) -> List[str]:
    """Render a tool's JSON-schema parameters as a markdown table."""
    properties: Dict[str, Any] = (parameters or {}).get("properties", {})
    if not properties:
        return ["_No parameters._", ""]

    required = set((parameters or {}).get("required", []))

    lines = [
        "| Parameter | Type | Required | Default | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, schema in properties.items():
        schema = schema or {}
        # Type can be a plain `type`, or an `anyOf`/`enum` combination.
        if "type" in schema:
            type_str = schema["type"]
        elif "anyOf" in schema:
            type_str = " \\| ".join(
                sub.get("type", "any") for sub in schema["anyOf"]
            )
        else:
            type_str = "any"

        is_required = "yes" if name in required else "no"
        default = _format_default(schema["default"]) if "default" in schema else ""
        description = (schema.get("description") or "").replace("\n", " ").strip()

        lines.append(
            f"| `{name}` | {type_str} | {is_required} | {default} | {description} |"
        )
    lines.append("")
    return lines


async def _collect_tools() -> List[Any]:
    tools = await mcp.list_tools()
    return sorted(tools, key=lambda t: t.name)


def build_markdown(tools: List[Any]) -> str:
    server_name = getattr(mcp, "name", "MCP Server")
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: List[str] = [
        f"# {server_name} - Available Tools",
        "",
        f"_Auto-generated by `scripts/generate_tools_md.py` on {generated_at}._",
        "",
        f"Total tools: **{len(tools)}**",
        "",
        "## Index",
        "",
    ]

    for tool in tools:
        summary = (tool.description or "").strip().splitlines()
        summary = summary[0] if summary else ""
        lines.append(f"- [`{tool.name}`](#{tool.name.replace('_', '-')}) - {summary}")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate tools.md documenting all MCP tools in this project."
    )
    parser.add_argument(
        "-o",
        "--output",
        default=os.path.join(PROJECT_ROOT, "tools.md"),
        help="Path to the markdown file to write (default: ./tools.md).",
    )
    args = parser.parse_args()

    tools = asyncio.run(_collect_tools())
    markdown = build_markdown(tools)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"Wrote {len(tools)} tools to {args.output}")


if __name__ == "__main__":
    main()